#!/usr/bin/python3

import sys
from subprocess import getoutput as terminal

if not 'Android' in terminal('uname -a'):
    import psutil

import os
import json
import time

HOME = terminal('echo $HOME')

try:
    sys.path.append('/usr/share/sysfetch')
except:
    conf = json.load(open('conf.json', 'r'))
    try:
        import distros
    except:
        print('Using sysfetch out of its git directory is possible only if you executed install.sh script')
else:
    import distros

    conf = json.load(open(f'{HOME}/.sysfetch/conf.json', 'r'))

unicodes = {
    'alpine': '\uF300',
    'macos': '\uF302',
    'arch': '\uF303',
    'debian': '\uF306',
    'kali': '\uF327',
    'parrot': '\uF329',
    'endeavour': '\uF322',
    'raspbian': '\uF315',
    'fedora' : '\uF30A',
    'manjaro': '\uF312',
    'centos': '\uF304',
    'opensuse': '\uF314',
    'redhat': '\uF316',
    'sabayon': '\uF317',
    'slackware': '\uF318',
    'mandriva': '\uF311',
    'mageia': '\uF310',
    'devuan': '\uF307',
    'tux' : '\uF31A'
}

colors = {
    'grey': '90m',
    'red': '31m',
    'yellow': '93m',
    'purple': '95m',
    'green': '32m',
    'lightblue': '94m',
    'blue': '34m',
    'orange': '33m',
    'aquagreen': '96m'
}

def makeNew():
    output = []
    cache = []

    asciiArt = 'tux'

    if 'Android' in terminal('uname -a'):
        asciiArt = 'android'
        osname = None

    else:
        osname = terminal('cat /etc/os-release | grep -w ID | awk -F \'=\' \'{ print $2 }\'').strip().lower()
        osSpecific = terminal('cat /etc/issue').strip().split(' ')[0].lower()

        if osSpecific in distros.distro.keys():
            asciiArt = osSpecific

        else:
            if osname in distros.distro.keys():
                asciiArt = osname

    if conf['ascii-art']:
        asciiArt = conf['ascii-art']

    asciiLogo = distros.distro[asciiArt][0]
    width = distros.distro[asciiArt][1]
    height = distros.distro[asciiArt][2]

    if conf['separator-unicode']:
        unicodeLogo = unicodes[conf['separator-unicode']]

    else:
        unicodeLogo = '\uF31A'
        if osname in unicodes.keys():

            for key in unicodes:
                if key.lower() in osname.lower():
                    unicodeLogo = unicodes[key]

        else:
            try:
                osLike = terminal('cat /etc/os-release | grep -w ID_LIKE | awk -F \'=\' \'{ print $2 }\'')

            except:
                pass

            else:
                for key in unicodes:

                    if key.lower() in osLike.lower():
                        unicodeLogo = unicodes[key]

    try:
        sent = psutil.net_io_counters().bytes_sent
        recv = psutil.net_io_counters().bytes_recv
        written = psutil.disk_io_counters().write_bytes
        red = psutil.disk_io_counters().read_bytes
        before = time.time()
    except: pass

    colorUnicode = f'\x1b[1;{color}'
    colorUnicodeBold = f'\x1b[7;{color}'
    white = '\x1b[00m'
    indent = f'\x1b[{width}C'
    down = '\n'

    output.append('{up}' + indent + '\x1b[1D' + colorUnicode + '' + white + f'{colorUnicodeBold} ' + terminal(
        'whoami') + f' {unicodeLogo} ' + terminal('uname -n') + ' ' + white + colorUnicode + '' + white + down)
    cache.append(
        '{up}' + indent + '\x1b[1D' + '{color_unicode}' + '' + white + '{color_unicode_bold} ' + '{username} ' +
        unicodeLogo + ' {hostname} ' + white + '{color_unicode}' + '' + white + down)

    if asciiArt == 'Android':
        distro = 'Android'

    else:
        distro = terminal('cat /etc/issue')
        distro = distro[0:distro.index('\\')]

    output.append(indent + colorUnicode + 'os: ' + white + distro + down)
    cache.append(indent + '{color_unicode}' + 'os: ' + white + distro + down)

    kernel = terminal('uname -r')
    output.append(indent + colorUnicode + 'kernel: ' + white + kernel + down)
    cache.append(indent + '{color_unicode}' + 'kernel: ' + white + '{kernel}' + down)

    shell = terminal('$SHELL --version').split('\n')[0]
    output.append(indent + colorUnicode + 'shell: ' + white + shell + down)
    cache.append(indent + '{color_unicode}' + 'shell: ' + white + '{shell}' + down)

    cpu = terminal('lscpu | grep "Model name" | awk -F \':\' \'{ print $2 }\'').strip().split('\n')[0]
    output.append(indent + colorUnicode + 'cpu: ' + white + cpu + down)
    cache.append(indent + '{color_unicode}' + 'cpu: ' + white + cpu + down)

    cpuarch = terminal('lscpu | grep Arch | awk -F \':\' \'{ print $2 }\'').strip()
    output.append(indent + colorUnicode + '    architecture: ' + white + cpuarch + down)
    cache.append(indent + '{color_unicode}' + '    architecture: ' + white + cpuarch + down)

    cpuCores = terminal('lscpu | grep "CPU(s)" -m 1 | awk -F \':\' \'{ print $2 }\'').strip()
    output.append(indent + colorUnicode + '    cores: ' + white + cpuCores + down)
    cache.append(indent + '{color_unicode}' + '    cores: ' + white + cpuCores + down)

    cpuThreads = terminal('echo $(lscpu | grep Thread | awk -F \':\' \'{ print $2 }\' && lscpu  | grep "CPU(s)" -m 1 | awk -F \':\' \'{ print $2 }\') | awk \'{ print $1 * $2 }\'')
    output.append(indent + colorUnicode + '    threads: ' + white + cpuThreads + down)
    cache.append(indent + '{color_unicode}' + '    threads: ' + white + cpuThreads + down)

    try:
        cpuUsage = str(psutil.cpu_percent()) + '%'
        output.append(indent + colorUnicode + '    usage: ' + white + cpuUsage + down)
        cache.append(indent + '{color_unicode}' + '    usage: ' + white + '{cpu_usage}' + down)
    except:
        pass

    try:
        cpuTemp = str(psutil.sensors_temperatures()['coretemp'][0].current) + ' C'
        output.append(indent + colorUnicode + '    temperature: ' + white + cpuTemp + down)
        cache.append(indent + '{color_unicode}' + '    temperature: ' + white + '{cpu_temperature}' + down)
    except:
        pass

    ram = str(round(
        float(terminal('cat /proc/meminfo | grep MemTotal | awk \'{ print $2 / 1024 / 1024 }\'').replace(',', '.')),
        2)) + ' GB'
    output.append(indent + colorUnicode + 'ram: ' + white + ram + down)
    cache.append(indent + '{color_unicode}' + 'ram: ' + white + ram + down)

    ramUsage = str(round(float(terminal(
        "echo $(cat /proc/meminfo | grep MemTotal | awk '{ print $2 }' && cat /proc/meminfo | grep MemAvailable | awk '{ print $2 }') | awk '{ print ($1 - $2) * 100 / $1 }'").replace(
        ',', '.')))) + '% (' + str(round(float(terminal(
        "echo $(cat /proc/meminfo | grep MemTotal | awk '{ print $2 }' && cat /proc/meminfo | grep MemAvailable | awk '{ print $2 }') | awk '{ print ($1 - $2) / 1024 / 1024 }'").replace(
        ',', '.')), 2)) + ' GB)'
    output.append(indent + colorUnicode + '    usage: ' + white + ramUsage + down)
    cache.append(indent + '{color_unicode}' + '    usage: ' + white + '{ram_usage}' + down)

    ramCached = terminal('cat /proc/meminfo | grep -m 1 "Cached" | awk  \'{ print $2 / 1024 " MB"}\'').strip()
    output.append(indent + colorUnicode + '    cached: ' + white + ramCached + down)
    cache.append(indent + '{color_unicode}' + '    cached: ' + white + '{ram_cached}' + down)

    swap = str(round(
        float(terminal('cat /proc/meminfo | grep "SwapTotal" | awk \'{ print $2 / 1024 / 1024 }\'').replace(',', '.')),
        2)) + ' GB'
    output.append(indent + colorUnicode + 'swap: ' + white + swap + down)
    cache.append(indent + '{color_unicode}' + 'swap: ' + white + swap + down)

    swapUsage = str(round(float(terminal(
        "echo $(cat /proc/meminfo | grep SwapTotal | awk '{ print $2 }' && cat /proc/meminfo | grep SwapFree | awk '{ print $2 }') | awk '{ print $1 ? ($1 - $2) * 100 / $1 : 0}'").replace(
        ',', '.')))) + '% (' + str(round(float(terminal(
        "echo $(cat /proc/meminfo | grep SwapTotal | awk '{ print $2 }' && cat /proc/meminfo | grep SwapFree | awk '{ print $2 }') | awk '{ print ($1 - $2) / 1024 / 1024 }'").replace(
        ',', '.')), 2)) + ' GB)'
    output.append(indent + colorUnicode + '    usage: ' + white + swapUsage + down)
    cache.append(indent + '{color_unicode}' + '    usage: ' + white + '{swap_usage}' + down)

    swapCached = terminal('cat /proc/meminfo | grep SwapCached | awk \'{ print $2 / 1024 }\'').strip() + ' MB'
    output.append(indent + colorUnicode + '    cached: ' + white + swapCached + down)
    cache.append(indent + '{color_unicode}' + '    cached: ' + white + '{swap_cached}' + down)

    try:
        totalStorage = terminal('lsblk | grep / -w | awk \'{ print $4}\'')
        output.append(indent + colorUnicode + 'storage: ' + white + totalStorage + down)
        cache.append(indent + '{color_unicode}' + 'storage: ' + white + totalStorage + down)
    except: pass

    try:
        usedStorage = terminal('lsblk -f -o FSUSE%,MOUNTPOINT | grep / -w | awk \'{ print $1 }\'')
        output.append(indent + colorUnicode + '    usage: ' + white + usedStorage + down)
        cache.append(indent + '{color_unicode}' + '    usage: ' + white + '{used_storage}' + down)
    except: pass

    gpu = terminal("lspci | grep VGA | awk -F 'controller:' '{ print $2 }'").strip()
    if not 'not found' in gpu and not 'pcilib' in gpu:
        output.append(indent + colorUnicode + 'gpu: ' + white + gpu + down)
        cache.append(indent + '{color_unicode}' + 'gpu: ' + white + gpu + down)

    processes = str(len(terminal('ps axu').split('\n')) - 1)
    output.append(indent + colorUnicode + 'processes: ' + white + processes + down)
    cache.append(indent + '{color_unicode}' + 'processes: ' + white + '{processes}' + down)

    ipv4 = terminal('hostname -I')
    if not 'invalid' in ipv4:
        output.append(indent + colorUnicode + 'ipv4: ' + white + ipv4 + down)
        cache.append(indent + '{color_unicode}' + 'ipv4: ' + white + '{ipv4}' + down)

    try:
        now = time.time()
        sentNow = psutil.net_io_counters().bytes_sent
        recvNow = psutil.net_io_counters().bytes_recv
        writtenNow = psutil.disk_io_counters().write_bytes
        redNow = psutil.disk_io_counters().read_bytes
    except:
        pass
    else:
        output.append(indent + colorUnicode + 'network speed: ' + white + down)
        cache.append(indent + colorUnicode + 'network speed: ' + white + down)
        output.append(
            indent + colorUnicode + '    upload: ' + white + str(round((sentNow-sent) / (now - before) / 1024, 2)) + ' kBps' + down)
        cache.append(
            indent + colorUnicode + '    upload: ' + white + '{upload}' + ' kBps' + down)
        output.append(
            indent + colorUnicode + '    download: ' + white + str(round((recvNow - recv) / (now - before) / 1024, 2)) + ' kBps' + down)
        cache.append(
            indent + colorUnicode + '    download: ' + white + '{download}' + ' kBps' + down)

        output.append(indent + colorUnicode + 'disk speed: ' + white + down)
        cache.append(indent + colorUnicode + 'disk speed: ' + white + down)
        output.append(
            indent + colorUnicode + '    writing: ' + white + str(round((writtenNow - written) / (now - before) / 1024, 2)) + ' kBps' + down)
        cache.append(
            indent + colorUnicode + '    writing: ' + white + '{writing}' + ' kBps' + down)
        output.append(
            indent + colorUnicode + '    reading: ' + white + str(round((redNow - red) / (now - before) / 1024, 2)) + ' kBps' + down)
        cache.append(
            indent + colorUnicode + '    reading: ' + white + '{reading}' + ' kBps' + down)

    output.append('{end}' + '\n')
    cache.append('{end}' + '\n')

    lines = len(output)

    up = f'\x1b[{height-1}A\x1b[999D'
    if height - lines < 0:
        end = ''
    else:
        end = f'\x1b[9999D\x1b[{height - lines}B'

    output[0] = output[0].replace('{up}', up)
    cache[0] = cache[0].replace('{up}', up)

    output.insert(0, colorUnicode + asciiLogo + white)
    cache.insert(0, colorUnicode + asciiLogo + white)

    output[-1] = output[-1].replace('{end}', end)
    cache[-1] = cache[-1].replace('{end}', end)

    print('')
    sys.stdout.write(''.join(output))
    print('')

    with open(HOME + '/.sysfetch/sysfetch.cache', 'w') as file:
        file.write(''.join(cache))


def printCached(color):
    with open(HOME + '/.sysfetch/sysfetch.cache', 'r') as cache:

        try:
            sent = psutil.net_io_counters().bytes_sent
            recv = psutil.net_io_counters().bytes_recv
            written = psutil.disk_io_counters().write_bytes
            red = psutil.disk_io_counters().read_bytes
            before = time.time()
        except:
            pass

        content = cache.read()

        if conf['default-color']:
            color = colors[conf['default-color']]

        colorUnicode = f'\x1b[1;{color}'
        colorUnicodeBold = f'\x1b[7;{color}'

        content = content.replace('{username}', terminal('whoami'))
        content = content.replace('{hostname}', terminal('uname -n'))
        content = content.replace('{color_unicode}', colorUnicode)
        content = content.replace('{color_unicode_bold}', colorUnicodeBold)
        content = content.replace('{kernel}', terminal('uname -r'))
        content = content.replace('{shell}', terminal('$SHELL --version').split('\n')[0])

        try:
            content = content.replace('{cpu_usage}', str(psutil.cpu_percent()) + '%')
        except: pass

        try:
            content = content.replace('{cpu_temperature}', str(psutil.sensors_temperatures()['coretemp'][0].current) + ' C')
        except: pass

        try:
            content = content.replace('{ram_usage}', str(round(float(terminal(
            "echo $(cat /proc/meminfo | grep MemTotal | awk '{ print $2 }' && cat /proc/meminfo | grep MemAvailable | awk '{ print $2 }') | awk '{ print ($1 - $2) * 100 / $1 }'").replace(
            ',', '.')))) + '% (' + str(round(float(terminal(
            "echo $(cat /proc/meminfo | grep MemTotal | awk '{ print $2 }' && cat /proc/meminfo | grep MemAvailable | awk '{ print $2 }') | awk '{ print ($1 - $2) / 1024 / 1024 }'").replace(
            ',', '.')), 2)) + ' GB)')
        except: pass

        try:
            content = content.replace('{ram_cached}', terminal(
                'cat /proc/meminfo | grep -m 1 "Cached" | awk  \'{ print $2 / 1024 " MB"}\'').strip())
        except: pass

        try:
            content = content.replace('{swap_usage}', str(round(float(terminal(
                "echo $(cat /proc/meminfo | grep SwapTotal | awk '{ print $2 }' && cat /proc/meminfo | grep SwapFree | awk '{ print $2 }') | awk '{ print $1 ? ($1 - $2) * 100 / $1 : 0}'").replace(
                ',', '.')))) + '% (' + str(round(float(terminal(
                "echo $(cat /proc/meminfo | grep SwapTotal | awk '{ print $2 }' && cat /proc/meminfo | grep SwapFree | awk '{ print $2 }') | awk '{ print ($1 - $2) / 1024 / 1024 }'").replace(
                ',', '.')), 2)) + ' GB)')
        except: pass

        try:
            content = content.replace('{swap_cached}', terminal(
               'cat /proc/meminfo | grep SwapCached | awk \'{ print $2 / 1024 }\'').strip() + ' MB')
        except: pass

        try:
            content = content.replace('{used_storage}', terminal('lsblk -f -o FSUSE%,MOUNTPOINT | grep / -w | awk \'{ print $1 }\''))
        except: pass

        content = content.replace('{processes}', str(len(terminal('ps axu').split('\n')) - 1))
        content = content.replace('{ipv4}', terminal('hostname -I'))

        try:
            now = time.time()
            sentNow = psutil.net_io_counters().bytes_sent
            recvNow = psutil.net_io_counters().bytes_recv
            writtenNow = psutil.disk_io_counters().write_bytes
            redNow = psutil.disk_io_counters().read_bytes

        except:
            pass

        else:
            content = content.replace('{upload}', str(round((sentNow - sent) / (now - before) / 1024, 2)))
            content = content.replace('{download}', str(round((recvNow - recv) / (now - before) / 1024, 2)))
            content = content.replace('{writing}', str(round((writtenNow - written) / (now - before) / 1024, 2)))
            content = content.replace('{reading}', str(round((redNow - red) / (now - before) / 1024, 2)))

        print('')
        sys.stdout.write(content)
        print('')


if __name__ == '__main__':
    color = colors['aquagreen']

    if conf['default-color']:
        color = colors[conf['default-color']]

    if not '.sysfetch' in os.listdir(HOME):
        terminal(f'mkdir  {HOME}/.sysfetch')

    if len(sys.argv) == 1:
        if 'sysfetch.cache' in os.listdir(HOME + '/.sysfetch') and not conf['always-recache']:
            printCached(color)

        else:
            makeNew()

    else:
        if '--help' in sys.argv or '-h' in sys.argv:
            print('''sysfetch [options] [arguments]

Command line system information tool written in Python

Options:
    recache             makes new cache file updating all static data 
    color               allows to set the color of teh text output 
    --help, -h          show this message and exit

Colors:
    red, yellow, grey, purple, green, lightblue, blue, orange, aquagreen (default)
    
To set a standard behaviuor, edit the file "conf.json" located in $HOME/.sysfetch/conf.json
For an example configutation, check at https://github.com/cpy-dev/sysfetch
            ''')
            sys.exit(0)
        
        if 'color' in sys.argv:
            colorIndex = sys.argv.index('color') + 1
            color = colors[sys.argv[colorIndex]]

        if 'recache' in sys.argv or conf['always-recache']:
            makeNew()
            
        else:
            printCached(color)
